### PR TITLE
! core: Advocate for singleton id generators, fix #55

### LINKED ISSUE #55: Should ID generation be a singleton?
Ran into an issue today where I finally needed to put an ID on something. Specifically it's an image button (no other way to identify it besides ID), which is created inside of a view rather than the activity. Even if I mixed `IdGeneration` into the activity to access it from my tests, I'd potentially get back different IDs since it will use a different cache. Ultimately I now have this in my application:

```
package ui

object Id extends macroid.IdGen(1000)
```

Should the `FullDsl` object just include a singleton instance?

### PR DESCRIPTION
**Pull request by stanch**
* Retired the IdGeneration trait
* Renamed IdGen to IdGenerator and made Tag an object
* Updated the documentation

### CODE REVIEW

**Comment by bennythomps** [comment]
:+1:

**Comment by stanch** [comment]
Merged.

**Comment by nightscape** [comment]
A little late to the party, but how about also adding the
```scala
object Id extends IdGenerator(start = 1000)
```
from the documentation to the library?

I guess most people don't care about specifying start values for IDs manually

**Comment by bennythomps** [comment]
Makes sense, especially as I try to start using it, I'm noticing a lot o' copy n paste.

**Pull request closed without merging**
