### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by Governa**
Some Tweaks that I found to be useful.

### CODE REVIEW

**Comment by bennythomps** [comment]
:+1:

**Comment by stanch** [comment]
Thanks!
Just a small detail — could you squash everything into a single commit with a message along these lines?
```
+ core: Add more contrib tweaks

* ImageTweaks: set image URI
* TextTweaks: use String as HTML
* TextTweaks: change input type class
```
I’m trying to more or less follow the [Spray.io commit message style](http://spray.io/project-info/contributing/).

**Comment by stanch** [comment]
I will look into the Travis problem, perhaps there is a new version of the build tools (although it’s strange, because I updated the Travis config just this week).

**Comment by stanch** [comment]
Travis config is fixed, just rebase, squash and I’ll be glad to merge :)

**Comment by Governa** [comment]
OK, I'll do it

Em dom, 15 de mar de 2015 14:45, Nick <notifications@github.com> escreveu:

**Comment by Governa** [comment]
Done.

I have two more changes that I could PR, but i don't know if you would like to have them in the main project.

They are:
 - Option[View] can find view
 - Seq is an effector

The first is useful when used with macroid's slot[View] and the second is the equivalent of "List is an effector" but with the more common type Seq

**Comment by stanch** [comment]
Thanks! I’ve changed your commit message a bit to include the `+` at the beginning, because it makes it easier to write changelogs. The updated commit is force-pushed, your authorship is preserved :)

> I have two more changes that I could PR, but i don't know if you would like to have them in the main project.

Please send them in! I think these are reasonable additions. Maybe `Effector[Seq]` should even replace `Effector[List]`, what do you think? Or even something more generic, such as `Effector[TraversableOnce]`...

**Pull request merged**
